const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={configured:false,servers:[],serverId:null,status:null,settings:null,logs:[],events:null,current:'servers',configFile:'config.json'};
async function api(url,opts={}){const headers=opts.body instanceof FormData?{}:{'Content-Type':'application/json'};if(state.serverId)headers['X-HSM-Server']=state.serverId;const res=await fetch(url,{...opts,headers:{...headers,...(opts.headers||{})}});let body=null;try{body=await res.json()}catch{}if(res.status===401&&!url.includes('/login')){showAuth(false);throw new Error('Authentication required')}if(!res.ok)throw new Error(body?.error||`${res.status} ${res.statusText}`);return body}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3000)}
function fmtBytes(n){if(!n)return'—';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i>1?1:0)} ${u[i]}`}
function fmtUptime(sec){if(!sec)return'—';const d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`}
function fmtDate(v){try{return new Date(v).toLocaleString()}catch{return v}}function fmtTime(v){try{return new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}catch{return''}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function selectedSummary(){return state.servers.find(s=>s.id===state.serverId)}
async function boot(){const b=await api('/api/bootstrap');state.configured=b.configured;if(!b.configured){showAuth(true);return}try{await api('/api/servers');showApp()}catch{showAuth(false)}}
function showAuth(setup){$('#app').classList.add('hidden');$('#auth').classList.remove('hidden');$('#auth-title').textContent=setup?'Create admin account':'Sign in';$('#auth-copy').textContent=setup?'Secure this server manager.':'Manage your Hytale servers.';$('#auth-submit').textContent=setup?'Create account':'Sign in';$('#auth-pass').autocomplete=setup?'new-password':'current-password';$('#auth-form').dataset.mode=setup?'setup':'login'}
async function showApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');await loadServers(true);if(state.serverId)await loadSelected();clearInterval(state.poll);state.poll=setInterval(async()=>{await loadServers(false);if(state.serverId&&state.current!=='servers')await refreshStatus()},2000);switchView(state.current)}
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();$('#auth-error').textContent='';const body={username:$('#auth-user').value.trim(),password:$('#auth-pass').value};try{await api($('#auth-form').dataset.mode==='setup'?'/api/bootstrap':'/api/login',{method:'POST',body:JSON.stringify(body)});showApp()}catch(err){$('#auth-error').textContent=err.message}});$('#logout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST'})}catch{}location.reload()});
$$('#nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-view-link]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewLink)));
function switchView(v){state.current=v;$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${v}`)?.classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const titles={servers:'Servers',dashboard:'Overview',console:'Console',config:'Files',mods:'Mods',backups:'Backups',setup:'Install',settings:'Settings'};$('#view-title').textContent=titles[v];const global=v==='servers';$('#top-status').classList.toggle('hidden',global);$('#top-start').classList.toggle('hidden',global);$('#top-context').textContent=global?'':(selectedSummary()?.serverName||'');loadCurrent()}
function loadCurrent(){if(state.current==='servers')renderFleet();if(!state.serverId)return;if(state.current==='mods')loadMods();if(state.current==='backups')loadBackups();if(state.current==='config')loadServerConfig();if(state.current==='setup')loadInstallStatus()}
async function loadServers(initial=false){try{state.servers=await api('/api/servers');if(!state.servers.length)return;const saved=localStorage.getItem('hsm-server');if(!state.serverId||!state.servers.some(s=>s.id===state.serverId)){state.serverId=(saved&&state.servers.some(s=>s.id===saved))?saved:state.servers[0].id}renderServerList();renderFleet();renderFleetStats();populateCloneSources();if(initial)$('#top-context').textContent=selectedSummary()?.serverName||''}catch(e){if(initial)toast(e.message,true)}}
function renderFleetStats(){const online=state.servers.filter(s=>s.running).length;$('#fleet-online').textContent=online;$('#fleet-total').textContent=state.servers.length;const installed=state.servers.filter(s=>s.installed).length;$('#fleet-summary').innerHTML=`<div><strong>${state.servers.length}</strong><span>Instances</span></div><div><strong>${online}</strong><span>Online</span></div><div><strong>${installed}</strong><span>Installed</span></div><div><strong>${state.servers.length-online}</strong><span>Stopped</span></div>`}
function renderServerList(){const el=$('#server-list');el.innerHTML=state.servers.map(s=>`<button class="server-list-item ${s.id===state.serverId?'active':''}" data-select-server="${esc(s.id)}"><span class="dot ${s.running?'online':s.installBusy?'busy':''}"></span><span class="server-list-copy"><b>${esc(s.serverName)}</b><small>UDP ${s.port}</small></span></button>`).join('');$$('[data-select-server]').forEach(b=>b.addEventListener('click',()=>selectServer(b.dataset.selectServer)))}
function renderFleet(){if(!$('#fleet-grid'))return;const grid=$('#fleet-grid');if(!state.servers.length){grid.innerHTML='<div class="empty-state" style="padding:16px">No servers configured.</div>';return}grid.innerHTML=state.servers.map(s=>`<article class="fleet-card ${s.id===state.serverId?'selected':''}"><button class="fleet-open" data-fleet-open="${esc(s.id)}"><div class="fleet-name"><strong>${esc(s.serverName)}${s.primary?'<span class="primary-tag">primary</span>':''}</strong><small>UDP ${s.port}</small></div><div class="fleet-cell fleet-status"><span class="dot ${s.running?'online':s.installBusy?'busy':''}"></span>${s.running?'Online':s.installBusy?'Installing':'Offline'}</div><div class="fleet-cell fleet-address">${esc(s.publicHost||location.hostname)}:${s.port}</div><div class="fleet-cell fleet-uptime">${s.running?fmtUptime(s.uptimeSeconds):'—'}</div><div class="fleet-cell fleet-files">${s.installed?'Ready':'Missing'}</div></button><div class="fleet-actions"><button class="btn small ${s.running?'':'success'}" data-fleet-action="${s.running?'stop':'start'}" data-id="${esc(s.id)}">${s.running?'Stop':'Start'}</button><button class="btn small" data-fleet-open="${esc(s.id)}">Open</button></div></article>`).join('');$$('[data-fleet-open]').forEach(b=>b.addEventListener('click',()=>selectServer(b.dataset.fleetOpen)));$$('[data-fleet-action]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();fleetAction(b.dataset.id,b.dataset.fleetAction)}))}
async function selectServer(id){if(id===state.serverId){switchView('dashboard');return}state.events?.close();state.events=null;state.serverId=id;localStorage.setItem('hsm-server',id);state.logs=[];renderServerList();switchView('dashboard');await loadSelected()}
async function loadSelected(){if(!state.serverId)return;await Promise.all([loadSettings(),refreshStatus(),loadLogs()]);connectEvents();loadCurrent()}
async function fleetAction(id,action){try{await api(`/api/servers/${encodeURIComponent(id)}/${action}`,{method:'POST'});toast(`${action==='start'?'Start':'Stop'} requested`);setTimeout(()=>loadServers(false),400)}catch(e){toast(e.message,true)}}
async function refreshStatus(){if(!state.serverId)return;try{state.status=await api('/api/status');renderStatus()}catch{}}
function renderStatus(){const s=state.status,on=s?.running,busy=s?.installBusy;$('#top-status').innerHTML=`<span class="dot ${on?'online':busy?'busy':''}"></span><span>${on?'Online':busy?'Installing':'Offline'}</span>`;$('#hero-dot').className='dot large '+(on?'online':busy?'busy':'');$('#hero-state').textContent=on?'ONLINE':busy?'INSTALLING':'OFFLINE';$('#metric-uptime').textContent=fmtUptime(s?.uptimeSeconds);$('#metric-memory').textContent=fmtBytes(s?.memoryBytes);$('#metric-memory-limit').textContent=fmtBytes(s?.memoryLimitBytes);$('#metric-installed').textContent=s?.installed?'Ready':'Missing';$('#memory-warning').classList.toggle('hidden',s?.meetsMinimumMemory!==false);$('#start-btn').disabled=on||busy||!s?.installed;$('#top-start').disabled=on||busy||!s?.installed;$('#stop-btn').disabled=!on;$('#restart-btn').disabled=!on;$('#top-start').textContent=on?'Running':s?.installed?'Start':'Install';if(state.settings){$('#metric-port').textContent=state.settings.port;updateAddress()}if(state.current==='config')setConfigEditState(!on)}
async function loadSettings(){if(!state.serverId)return;state.settings=await api('/api/settings');const s=state.settings;$('#server-name').textContent=s.serverName;$('#top-context').textContent=s.serverName;$('#set-name').value=s.serverName;$('#set-host').value=s.publicHost||'';$('#set-port').value=s.port;$('#set-port').min=s.portMin||1;$('#set-port').max=s.portMax||65535;$('#port-help').textContent=`Published UDP range: ${s.portMin||1}–${s.portMax||65535}. Each server must use a unique port.`;$('#set-backup').value=s.backupFrequency;$('#set-xms').value=s.memoryMin;$('#set-xmx').value=s.memoryMax;$('#set-args').value=s.extraArgs||'';$('#set-autostart').checked=s.autoStart;$('#metric-port').textContent=s.port;const sel=selectedSummary();$('#delete-server').disabled=!!sel?.primary;$('#delete-server').title=sel?.primary?'The primary server is retained for existing storage compatibility.':'';updateAddress()}
function updateAddress(){const s=state.settings;if(!s)return;$('#connect-address').textContent=`${s.publicHost||location.hostname}:${s.port}`}
$('#copy-address').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#connect-address').textContent);toast('Address copied')}catch{toast('Could not copy address',true)}});
for(const id of['start-btn','top-start','setup-start'])$('#'+id).addEventListener('click',()=>serverAction('start'));$('#stop-btn').addEventListener('click',()=>serverAction('stop'));$('#restart-btn').addEventListener('click',()=>serverAction('restart'));
async function serverAction(action){if(action==='start'&&state.status&&!state.status.installed){switchView('setup');return}try{await api(`/api/server/${action}`,{method:'POST'});toast(`${action[0].toUpperCase()+action.slice(1)} requested`);setTimeout(async()=>{await refreshStatus();await loadServers(false)},450)}catch(e){toast(e.message,true)}}
async function loadLogs(){if(!state.serverId)return;try{state.logs=await api('/api/logs');renderLogs()}catch{}}
function renderLogs(){const out=$('#console-output');out.innerHTML=state.logs.map(logHTML).join('');if($('#auto-scroll').checked)out.scrollTop=out.scrollHeight;renderMiniLog()}
function renderMiniLog(){const recent=state.logs.slice(-8);$('#mini-log').innerHTML=recent.map(x=>`<div class="mini-line ${esc(x.source)}"><span class="time">${fmtTime(x.time)}</span>${esc(x.line)}</div>`).join('')||'<span class="muted">No server output yet.</span>'}
function logHTML(x){return`<div class="log-line ${esc(x.source)}"><span class="stamp">${fmtTime(x.time)}</span><span class="source">${esc(x.source)}</span>${esc(x.line)}</div>`}
function connectEvents(){state.events?.close();if(!state.serverId)return;const id=state.serverId;const es=new EventSource(`/api/events?server=${encodeURIComponent(id)}`);state.events=es;es.onmessage=e=>{if(id!==state.serverId)return;try{const line=JSON.parse(e.data);state.logs.push(line);if(state.logs.length>2500)state.logs=state.logs.slice(-2500);const out=$('#console-output');out.insertAdjacentHTML('beforeend',logHTML(line));if($('#auto-scroll').checked)out.scrollTop=out.scrollHeight;renderMiniLog()}catch{}}}
$('#console-form').addEventListener('submit',async e=>{e.preventDefault();const i=$('#console-command'),command=i.value.trim();if(!command)return;try{await api('/api/console',{method:'POST',body:JSON.stringify({command})});i.value=''}catch(e){toast(e.message,true)}});$('#clear-console').addEventListener('click',()=>{$('#console-output').innerHTML=''});
$$('[data-action]').forEach(b=>b.addEventListener('click',async()=>{try{if(b.dataset.action==='auth'){await api('/api/auth/device',{method:'POST'});switchView('console');toast('Device login started')}if(b.dataset.action==='backup'){await api('/api/backups/native',{method:'POST'});toast('Backup requested')}}catch(e){toast(e.message,true)}}));
$$('[data-update]').forEach(b=>b.addEventListener('click',async()=>{const action=b.dataset.update;if(action==='apply'&&!confirm('Apply the staged Hytale update to this server now?'))return;try{await api(`/api/update/${action}`,{method:'POST'});switchView('console');toast(`Update ${action} requested`)}catch(e){toast(e.message,true)}}));
$('#setup-auth').addEventListener('click',async()=>{try{await api('/api/auth/device',{method:'POST'});switchView('console');toast('Device login started')}catch(e){toast(e.message,true)}});
function setConfigEditState(editable){$('#server-config').disabled=!editable;$('#save-config').disabled=!editable;$('#config-running-note').classList.toggle('hidden',editable)}
async function loadServerConfig(){state.configFile=$('#config-file').value;try{const d=await api(`/api/server/file/${encodeURIComponent(state.configFile)}`);let c=d.content;try{c=JSON.stringify(JSON.parse(c),null,2)}catch{}$('#server-config').value=c;$('#config-note').textContent=d.exists?`Loaded ${d.name}`:`${d.name} does not exist yet`;setConfigEditState(d.editable)}catch(e){toast(e.message,true)}}
$('#config-file').addEventListener('change',loadServerConfig);$('#reload-config').addEventListener('click',loadServerConfig);$('#save-config').addEventListener('click',async()=>{try{JSON.parse($('#server-config').value);await api(`/api/server/file/${encodeURIComponent($('#config-file').value)}`,{method:'PUT',body:JSON.stringify({content:$('#server-config').value})});toast('File saved')}catch(e){toast(e.message,true)}});
async function loadMods(){try{const mods=await api('/api/mods'),el=$('#mods-list');el.classList.toggle('empty-state',!mods.length);el.innerHTML=mods.map(m=>`<div class="file-row"><span class="name">${esc(m.name)}</span><span class="meta">${fmtBytes(m.size)}</span><span class="meta">${fmtDate(m.modified)}</span><button data-del-mod="${encodeURIComponent(m.name)}">Remove</button></div>`).join('')||'No mods installed.';$$('[data-del-mod]').forEach(b=>b.addEventListener('click',()=>deleteMod(decodeURIComponent(b.dataset.delMod))))}catch(e){toast(e.message,true)}}
$('#mod-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{await api('/api/mods/upload',{method:'POST',body:fd});toast('Mod uploaded');loadMods()}catch(err){toast(err.message,true)}finally{e.target.value=''}});async function deleteMod(name){if(!confirm(`Remove ${name} from this server?`))return;try{await api(`/api/mods/${encodeURIComponent(name)}`,{method:'DELETE'});toast('Mod removed');loadMods()}catch(e){toast(e.message,true)}}
async function loadBackups(){try{const d=await api('/api/backups');renderFiles($('#native-backups'),d.native);const el=$('#snapshots');el.classList.toggle('empty-state',!d.snapshots.length);el.innerHTML=d.snapshots.map(m=>`<div class="file-row"><span class="name">${esc(m.name)}</span><span class="meta">${fmtBytes(m.size)}</span><span class="meta">${fmtDate(m.modified)}</span><span><button data-restore="${encodeURIComponent(m.name)}">Restore</button> <button data-del-snap="${encodeURIComponent(m.name)}">Delete</button></span></div>`).join('')||'No snapshots found.';$$('[data-restore]').forEach(b=>b.addEventListener('click',()=>restoreSnapshot(decodeURIComponent(b.dataset.restore))));$$('[data-del-snap]').forEach(b=>b.addEventListener('click',()=>deleteSnapshot(decodeURIComponent(b.dataset.delSnap))))}catch(e){toast(e.message,true)}}
function renderFiles(el,files){el.classList.toggle('empty-state',!files.length);el.innerHTML=files.map(m=>`<div class="file-row"><span class="name">${esc(m.name)}</span><span class="meta">${fmtBytes(m.size)}</span><span class="meta">${fmtDate(m.modified)}</span><span></span></div>`).join('')||'No backups found.'}
$('#native-backup').addEventListener('click',async()=>{try{await api('/api/backups/native',{method:'POST'});toast('Backup requested');setTimeout(loadBackups,1800)}catch(e){toast(e.message,true)}});$('#snapshot-backup').addEventListener('click',async()=>{try{await api('/api/backups/snapshot',{method:'POST'});toast('Snapshot created');loadBackups()}catch(e){toast(e.message,true)}});async function restoreSnapshot(name){if(!confirm(`Restore ${name} to this server? Hytale Server Manager will create a safety snapshot first.`))return;try{const r=await api(`/api/backups/${encodeURIComponent(name)}/restore`,{method:'POST'});toast(`Restored. Safety copy: ${r.safetySnapshot}`);loadBackups()}catch(e){toast(e.message,true)}}async function deleteSnapshot(name){if(!confirm(`Delete ${name}?`))return;try{await api(`/api/backups/${encodeURIComponent(name)}`,{method:'DELETE'});toast('Snapshot deleted');loadBackups()}catch(e){toast(e.message,true)}}
async function loadInstallStatus(){try{const d=await api('/api/install/status');$('#install-state').innerHTML=d.installed?`<b style="color:var(--green)">Server files installed</b><br><span class="muted">${esc(d.paths.game)}</span>`:`<b>Server files not installed</b><br><span class="muted">Shared downloader: ${d.downloaderPresent?'ready':'not uploaded'} · Instance game.zip: ${d.bundlePresent?'found':'not found'}${d.busy?' · installer running':''}</span>`;$('#run-downloader').disabled=d.busy||!d.downloaderPresent||d.installed;$('#import-local').disabled=d.busy||!d.bundlePresent||d.installed}catch(e){toast(e.message,true)}}
$('#downloader-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{await api('/api/install/downloader',{method:'POST',body:fd});toast('Shared Hytale downloader ready');loadInstallStatus()}catch(err){toast(err.message,true)}finally{e.target.value=''}});$('#run-downloader').addEventListener('click',async()=>{try{await api('/api/install/run-downloader',{method:'POST'});toast('Downloader started');switchView('console')}catch(e){toast(e.message,true)}});$('#import-local').addEventListener('click',async()=>{try{await api('/api/install/import-local',{method:'POST'});toast('Import started');switchView('console')}catch(e){toast(e.message,true)}});
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const s={id:state.serverId,serverName:$('#set-name').value.trim(),publicHost:$('#set-host').value.trim(),port:+$('#set-port').value,backupFrequency:+$('#set-backup').value,memoryMin:$('#set-xms').value.trim(),memoryMax:$('#set-xmx').value.trim(),extraArgs:$('#set-args').value.trim(),autoStart:$('#set-autostart').checked,storageDir:state.settings.storageDir||''};try{state.settings=await api('/api/settings',{method:'PUT',body:JSON.stringify(s)});await loadServers(false);await loadSettings();renderStatus();toast('Server settings saved')}catch(e){toast(e.message,true)}});
$('#delete-server').addEventListener('click',async()=>{const s=selectedSummary();if(!s||s.primary)return;if(!confirm(`Delete ${s.serverName}? Its server files, world, mods and snapshots will be permanently removed.`))return;try{await api(`/api/servers/${encodeURIComponent(s.id)}`,{method:'DELETE'});toast('Server deleted');state.serverId=null;await loadServers(true);await loadSelected();switchView('servers')}catch(e){toast(e.message,true)}});

const dialog=$('#server-dialog');function openServerDialog(){const ports=state.settings||{};$('#new-server-port').value='';$('#new-port-help').textContent=ports.portMin?`Leave blank for the next available port in ${ports.portMin}–${ports.portMax}.`:'Leave blank for the next available published port.';dialog.showModal()}function closeServerDialog(){dialog.close()}$('#add-server-side').addEventListener('click',openServerDialog);$('#add-server-main').addEventListener('click',openServerDialog);$('#close-server-dialog').addEventListener('click',closeServerDialog);$('#cancel-server-dialog').addEventListener('click',closeServerDialog);
function populateCloneSources(){const sel=$('#new-server-source'),current=sel.value;sel.innerHTML='<option value="">Blank server — install files after creation</option>'+state.servers.filter(s=>s.installed).map(s=>`<option value="${esc(s.id)}">Clone ${esc(s.serverName)} (new world)</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}
$('#server-create-form').addEventListener('submit',async e=>{e.preventDefault();const body={name:$('#new-server-name').value.trim(),port:+$('#new-server-port').value||0,sourceServerId:$('#new-server-source').value};try{const s=await api('/api/servers',{method:'POST',body:JSON.stringify(body)});closeServerDialog();toast('Server created');await loadServers(false);await selectServer(s.id);if(!body.sourceServerId)switchView('setup')}catch(err){toast(err.message,true)}});
boot().catch(e=>{document.body.innerHTML=`<pre style="padding:30px;color:#e29a96">${esc(e.stack||e.message)}</pre>`});
